/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.isuru.dinemore.view;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.isuru.dinemore.controller.ReceptionController;
import lk.isuru.dinemore.dto.RecepDTO;
import lk.isuru.dinemore.observer.Observer;

/**
 *
 * @author ISURU UMAYANGA
 */
public class ReceptionForm extends javax.swing.JFrame implements Observer{

    private DefaultTableModel dtm;
    /**
     * Creates new form ReceptionForm
     */
   
    public ReceptionForm() throws RemoteException,Exception {
        initComponents();
//        jLabel3.setBackground(new java.awt.Color(0,0,0,170));
        loadAllCustomers();
        getDateAndTime();
        getClock();
        UnicastRemoteObject.exportObject(this, 0);
        ReceptionController.getSubeject().registerObserver(this);
    }
    int avqty;
    String cstatus;

        private void getDateAndTime() {
        Date date = new Date();
        SimpleDateFormat simpledateformat = new SimpleDateFormat("yyyy-MM-dd");
        String new_DATE = simpledateformat.format(date);
        lbldate.setText(new_DATE);

    }
    private void loadAllCustomers() {
        dtm = (DefaultTableModel) tblorder.getModel();
        dtm.setRowCount(0);
        try {
            List<RecepDTO> orders = ReceptionController.getAllCustomers();
            if (orders == null) {
                return;
            }

            for (RecepDTO recepDTO : orders) {
                Object[] rowData = {
                    recepDTO.getOid(),
                    recepDTO.getCid(),
                    recepDTO.getTpNo(),
                    recepDTO.getTime(),
                    recepDTO.getQty(),
                    recepDTO.getStatus()
                };
                dtm.addRow(rowData);
            }

        } catch (Exception ex) {
            Logger.getLogger(ReceptionForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void getClock() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date curDate = new Date();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("HH:mm:ss aa");
                    String currentTime = dateFormat.format(curDate);

                    lbltime.setText(currentTime);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        JOptionPane.showMessageDialog(ReceptionForm.this, "Database Error...");
                    }
                }
            }
        }).start();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtrid = new javax.swing.JTextField();
        txtcustname = new javax.swing.JTextField();
        txtoid = new javax.swing.JTextField();
        txttp = new javax.swing.JTextField();
        jsqty = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblorder = new javax.swing.JTable();
        btnplace_order = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Reception ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/isuru/dinemore/view/image/icons8-front-desk-100 (2).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 90));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel2.setText("Manage Bun Orders");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 450, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Order ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Customer Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TP");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("QTY");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtrid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtridActionPerformed(evt);
            }
        });
        jPanel1.add(txtrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 230, 30));

        txtcustname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtcustname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtcustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 230, 30));

        txtoid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoidActionPerformed(evt);
            }
        });
        jPanel1.add(txtoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 210, 30));

        txttp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txttp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttpActionPerformed(evt);
            }
        });
        jPanel1.add(txttp, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 210, 30));
        jPanel1.add(jsqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 230, 30));

        tblorder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "Customer Name", "Telephone", "Time", "QTY", "Status"
            }
        ));
        tblorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblorderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblorder);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 850, 130));

        btnplace_order.setBackground(new java.awt.Color(51, 51, 255));
        btnplace_order.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnplace_order.setText("DONE");
        btnplace_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplace_orderActionPerformed(evt);
            }
        });
        jPanel1.add(btnplace_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 313, 140, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/isuru/dinemore/view/image/blur-bread-buns-1269665.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 870, 430));

        lbldate.setBackground(new java.awt.Color(102, 102, 102));
        lbldate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbldate.setForeground(new java.awt.Color(102, 102, 102));
        lbldate.setText("Date");
        jPanel1.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        lbltime.setBackground(new java.awt.Color(102, 102, 102));
        lbltime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltime.setForeground(new java.awt.Color(102, 102, 102));
        lbltime.setText("Time");
        jPanel1.add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnplace_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplace_orderActionPerformed
       try {
            String ststus = "Send To Kichen";

            int qty = Integer.parseInt(jsqty.getValue() + "");

            RecepDTO orderDTO = new RecepDTO(
                    txtoid.getText(),
                    txtrid.getText(),
                    lbldate.getText(),
                    lbltime.getText(),
                    txtcustname.getText(),
                    txttp.getText(),
                    qty,
                    ststus
            );
            boolean addorder = ReceptionController.placeOrder(orderDTO);
            if (addorder) {
                JOptionPane.showMessageDialog(this, "Order Added");
                loadAllCustomers();
            } else {
                JOptionPane.showMessageDialog(this, "Failed");
            }
        } catch (Exception ex) {
            Logger.getLogger(ReceptionForm.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_btnplace_orderActionPerformed

    private void tblorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblorderMouseClicked
        int selectedRow = tblorder.getSelectedRow();
        String oid = dtm.getValueAt(selectedRow, 0).toString();
        String cusname = dtm.getValueAt(selectedRow, 1).toString();
        String tp = dtm.getValueAt(selectedRow, 2).toString();
        String tqty = dtm.getValueAt(selectedRow, 4).toString();
        cstatus = dtm.getValueAt(selectedRow, 5).toString();
        avqty = Integer.parseInt(tqty);
        txtoid.setText(oid);
        txtcustname.setText(cusname);
        txttp.setText(tp);
        
    }//GEN-LAST:event_tblorderMouseClicked

    private void txtridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtridActionPerformed
        txtcustname.requestFocus();
    }//GEN-LAST:event_txtridActionPerformed

    private void txtcustnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustnameActionPerformed
        txtoid.requestFocus();
    }//GEN-LAST:event_txtcustnameActionPerformed

    private void txtoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoidActionPerformed
        txttp.requestFocus();
    }//GEN-LAST:event_txtoidActionPerformed

    private void txttpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttpActionPerformed
        jsqty.requestFocus();
    }//GEN-LAST:event_txttpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ReceptionForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ReceptionForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnplace_order;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jsqty;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTable tblorder;
    private javax.swing.JTextField txtcustname;
    private javax.swing.JTextField txtoid;
    private javax.swing.JTextField txtrid;
    private javax.swing.JTextField txttp;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateObservers() throws Exception {
        loadAllCustomers();
    }

    



   
}
